import { useEffect, useMemo, useState } from "react";
import { branchesApi, examsApi, subjectsApi, universitiesApi } from "../api.js";

const makeQuestion = () => ({ question_text: "", solution_text: "", choices: Array.from({ length: 4 }, (_, i) => ({ choice_text: "", is_correct: i === 0 })) });
const tabs = [{ id: "universities", label: "Universités", icon: "🎓" }, { id: "branches", label: "Branches", icon: "🏫" }, { id: "subjects", label: "Matières", icon: "📘" }, { id: "qcms", label: "QCM", icon: "📝" }];

function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="management-modal" onMouseDown={(e) => e.stopPropagation()}><button className="management-modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>; }
function Empty({ text }) { return <div className="management-empty"><span>◌</span>{text}</div>; }

export default function Management() {
  const [active, setActive] = useState("universities"); const [modal, setModal] = useState(null); const [notice, setNotice] = useState(""); const [editing, setEditing] = useState(null); const [editName, setEditName] = useState("");
  const [data, setData] = useState([]); const [exams, setExams] = useState([]);
  const [university, setUniversity] = useState({ name: "", category: "Universities", description: "" }); const [branch, setBranch] = useState({ university_id: "", name: "", description: "" }); const [subject, setSubject] = useState({ branch_id: "", name: "", level: "" }); const [qcm, setQcm] = useState({ subject_id: "", year: new Date().getFullYear(), title: "", duration_minutes: "", is_published: true }); const [selectedExam, setSelectedExam] = useState(""); const [question, setQuestion] = useState(makeQuestion);
  const branches = useMemo(() => data.flatMap((u) => u.branches.map((b) => ({ ...b, university: u.name }))), [data]);
  const subjects = useMemo(() => branches.flatMap((b) => b.subjects.map((s) => ({ ...s, branch: b.name, university: b.university }))), [branches]);
  const refresh = async () => { const [u, e] = await Promise.all([universitiesApi.list(), examsApi.list()]); setData(u); setExams(e); };
  useEffect(() => { refresh().catch((e) => setNotice(e.message)); }, []);
  const submit = (api, state, reset) => async (e) => { e.preventDefault(); try { await api(state); reset(); setModal(null); setNotice("Ajouté avec succès."); await refresh(); } catch (err) { setNotice(err.message); } };
  const openEdit = (api, id, name, label) => { setEditing({ api, id, label }); setEditName(name); setModal("edit"); };
  const saveEdit = async (e) => { e.preventDefault(); if (!editName.trim()) return; try { await editing.api(editing.id, { name: editName.trim() }); setModal(null); setEditing(null); setNotice("Mis à jour."); await refresh(); } catch (err) { setNotice(err.message); } };
  const addQuestion = async (e) => { e.preventDefault(); try { await examsApi.addQuestion(selectedExam, question); setQuestion(makeQuestion()); setModal(null); setNotice("Question ajoutée."); } catch (err) { setNotice(err.message); } };
  const openQuestion = (id) => { setSelectedExam(id); setModal("question"); };

  const modalContent = modal === "university" ? <Modal title="Ajouter une université" onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={submit(universitiesApi.create, university, () => setUniversity({ name: "", category: "Universities", description: "" }))}><label>Nom<input required value={university.name} onChange={(e) => setUniversity({ ...university, name: e.target.value })} placeholder="Université Mohammed V"/></label><label>Catégorie<input value={university.category} onChange={(e) => setUniversity({ ...university, category: e.target.value })}/></label><label>Description<textarea value={university.description} onChange={(e) => setUniversity({ ...university, description: e.target.value })}/></label><button className="btn btn-primary">Ajouter l’université</button></form></Modal>
    : modal === "branch" ? <Modal title="Ajouter une branche" onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={submit(branchesApi.create, branch, () => setBranch({ university_id: "", name: "", description: "" }))}><label>Université<select required value={branch.university_id} onChange={(e) => setBranch({ ...branch, university_id: e.target.value })}><option value="">Sélectionner</option>{data.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Nom<input required value={branch.name} onChange={(e) => setBranch({ ...branch, name: e.target.value })} placeholder="ENSIAS / Médecine…"/></label><label>Description<textarea value={branch.description} onChange={(e) => setBranch({ ...branch, description: e.target.value })}/></label><button className="btn btn-primary">Ajouter la branche</button></form></Modal>
    : modal === "subject" ? <Modal title="Ajouter une matière" onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={submit(subjectsApi.create, subject, () => setSubject({ branch_id: "", name: "", level: "" }))}><label>Branche<select required value={subject.branch_id} onChange={(e) => setSubject({ ...subject, branch_id: e.target.value })}><option value="">Sélectionner</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.university} — {b.name}</option>)}</select></label><label>Matière<input required value={subject.name} onChange={(e) => setSubject({ ...subject, name: e.target.value })} placeholder="Mathématiques"/></label><label>Niveau<input value={subject.level} onChange={(e) => setSubject({ ...subject, level: e.target.value })} placeholder="Bac+2"/></label><button className="btn btn-primary">Ajouter la matière</button></form></Modal>
    : modal === "qcm" ? <Modal title="Créer le QCM annuel" onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={submit(examsApi.create, qcm, () => setQcm({ subject_id: "", year: new Date().getFullYear(), title: "", duration_minutes: "", is_published: true }))}><label>Matière<select required value={qcm.subject_id} onChange={(e) => setQcm({ ...qcm, subject_id: e.target.value })}><option value="">Sélectionner</option>{subjects.map((s) => <option key={s.id} value={s.id}>{s.university} — {s.branch} — {s.name}</option>)}</select></label><div className="management-form-row"><label>Année<input required type="number" value={qcm.year} onChange={(e) => setQcm({ ...qcm, year: e.target.value })}/></label><label>Durée<input type="number" value={qcm.duration_minutes} onChange={(e) => setQcm({ ...qcm, duration_minutes: e.target.value })} placeholder="Minutes"/></label></div><label>Titre (optionnel)<input value={qcm.title} onChange={(e) => setQcm({ ...qcm, title: e.target.value })}/></label><label className="management-check"><input type="checkbox" checked={qcm.is_published} onChange={(e) => setQcm({ ...qcm, is_published: e.target.checked })}/><span>Publier immédiatement</span></label><button className="btn btn-primary">Créer le QCM</button></form></Modal>
    : modal === "question" ? <Modal title="Ajouter une question" onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={addQuestion}><label>QCM<select required value={selectedExam} onChange={(e) => setSelectedExam(e.target.value)}>{exams.map((e) => <option key={e.id} value={e.id}>{e.title} · {e.year}</option>)}</select></label><label>Question<textarea required value={question.question_text} onChange={(e) => setQuestion({ ...question, question_text: e.target.value })}/></label><div className="management-choices">{question.choices.map((c, i) => <label className={`management-choice ${c.is_correct ? "correct" : ""}`} key={i}><input type="radio" name="correct" checked={c.is_correct} onChange={() => setQuestion({ ...question, choices: question.choices.map((item, idx) => ({ ...item, is_correct: idx === i })) })}/><span>{String.fromCharCode(65 + i)}</span><input required value={c.choice_text} onChange={(e) => { const choices = [...question.choices]; choices[i] = { ...c, choice_text: e.target.value }; setQuestion({ ...question, choices }); }} placeholder={`Réponse ${i + 1}`}/></label>)}</div><label>Correction<textarea value={question.solution_text} onChange={(e) => setQuestion({ ...question, solution_text: e.target.value })}/></label><button className="btn btn-primary">Ajouter la question</button></form></Modal>
    : modal === "edit" && editing ? <Modal title={`Modifier ${editing.label}`} onClose={() => setModal(null)}><form className="management-modal-form" onSubmit={saveEdit}><label>Nouveau nom<input autoFocus required value={editName} onChange={(e) => setEditName(e.target.value)}/></label><button className="btn btn-primary">Enregistrer les modifications</button></form></Modal> : null;

  const list = active === "universities" ? <div className="management-list">{data.map((u) => <article className="management-list-card" key={u.id}><div className="list-icon">🎓</div><div><h3>{u.name}</h3><p>{u.description || "Aucune description"}</p><small>{u.branches.length} branche(s)</small></div><button className="btn btn-secondary btn-sm" onClick={() => openEdit(universitiesApi.update, u.id, u.name, "l’université")}>Modifier</button></article>)}{data.length === 0 && <Empty text="Aucune université créée."/>}</div>
    : active === "branches" ? <div className="management-list">{branches.map((b) => <article className="management-list-card" key={b.id}><div className="list-icon">🏫</div><div><h3>{b.name}</h3><p>{b.university}</p><small>{b.subjects.length} matière(s)</small></div><button className="btn btn-secondary btn-sm" onClick={() => openEdit(branchesApi.update, b.id, b.name, "la branche")}>Modifier</button></article>)}{branches.length === 0 && <Empty text="Ajoutez d’abord une université, puis une branche."/>}</div>
    : active === "subjects" ? <div className="management-list">{subjects.map((s) => <article className="management-list-card" key={s.id}><div className="list-icon">📘</div><div><h3>{s.name}</h3><p>{s.university} · {s.branch}</p><small>{s.level || "Niveau non défini"}</small></div><button className="btn btn-secondary btn-sm" onClick={() => openEdit(subjectsApi.update, s.id, s.name, "la matière")}>Modifier</button></article>)}{subjects.length === 0 && <Empty text="Ajoutez d’abord une branche, puis une matière."/>}</div>
    : <div className="management-list">{exams.map((e) => <article className="management-list-card" key={e.id}><div className="list-icon">📝</div><div><h3>{e.title}</h3><p>{e.subject_name || "Matière"} · {e.university_name || "Université"}</p><small>{e.year || "Année non définie"} {e.is_published ? "· Publié" : "· Brouillon"}</small></div><div className="list-actions"><button className="btn btn-secondary btn-sm" onClick={() => openQuestion(e.id)}>+ Question</button><button className="btn btn-secondary btn-sm" onClick={() => openEdit(examsApi.update, e.id, e.title, "le QCM")}>Modifier</button></div></article>)}{exams.length === 0 && <Empty text="Créez une matière puis son QCM annuel."/>}</div>;
  const addLabel = active === "universities" ? "Ajouter une université" : active === "branches" ? "Ajouter une branche" : active === "subjects" ? "Ajouter une matière" : "Créer un QCM";
  const modalName = active === "universities" ? "university" : active === "branches" ? "branch" : active === "subjects" ? "subject" : "qcm";

  return <main className="page management-page"><header className="management-hero"><div><div className="section-label">⊙ ESPACE PROFESSEUR</div><h1>Gestion académique</h1><p>Université → branche → matière → QCM annuel</p></div></header>{notice && <div className="management-notice">{notice}</div>}<div className="management-tabs">{tabs.map((tab) => <button key={tab.id} className={active === tab.id ? "active" : ""} onClick={() => setActive(tab.id)}><span>{tab.icon}</span>{tab.label}</button>)}</div><section className="management-panel"><div className="management-panel-head"><div><h2>{tabs.find((tab) => tab.id === active).label}</h2><p>Consultez et gérez les éléments existants.</p></div><button className="btn btn-primary" onClick={() => setModal(modalName)}>+ {addLabel}</button></div>{list}</section>{modalContent}</main>;
}
