import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { examsApi } from "../api.js";
import MathText from "../components/MathText.jsx";

const blankQuestion = () => ({ question_text: "", solution_text: "", choices: Array.from({ length: 4 }, (_, i) => ({ choice_text: "", is_correct: i === 0 })) });
function Preview({ value }) { return <div className="qcm-math-preview">{value ? <MathText text={value}/> : <span>Le rendu apparaîtra ici.</span>}</div>; }

export default function QcmEditor() {
  const { examId } = useParams(); const navigate = useNavigate();
  const [exam, setExam] = useState(null); const [draft, setDraft] = useState(blankQuestion); const [selectedId, setSelectedId] = useState(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { const data = await examsApi.get(examId); setExam(data); setLoading(false); return data; };
  useEffect(() => { load().catch((e) => { setNotice(e.message); setLoading(false); }); }, [examId]);
  const select = (question) => { setSelectedId(question.id); setDraft({ question_text: question.question_text || "", solution_text: question.solution_text || "", choices: question.choices.map((c) => ({ choice_text: c.choice_text, is_correct: Boolean(c.is_correct) })) }); };
  const newQuestion = () => { setSelectedId(null); setDraft(blankQuestion()); };
  const save = async (e) => { e.preventDefault(); try { if (selectedId) await examsApi.updateQuestion(selectedId, draft); else await examsApi.addQuestion(examId, draft); const data = await load(); const saved = selectedId ? data.questions.find((q) => q.id === selectedId) : data.questions.at(-1); if (saved) select(saved); setNotice(selectedId ? "Question modifiée." : "Question ajoutée."); } catch (err) { setNotice(err.message); } };
  const remove = async () => { if (!selectedId || !window.confirm("Supprimer cette question ?")) return; try { await examsApi.deleteQuestion(selectedId); await load(); newQuestion(); setNotice("Question supprimée."); } catch (err) { setNotice(err.message); } };
  const setChoice = (index, next) => { const choices = [...draft.choices]; choices[index] = { ...choices[index], ...next }; setDraft({ ...draft, choices }); };
  if (loading) return <div className="center-msg"><span className="spinner" /></div>;
  if (!exam) return <div className="page"><p className="error-msg">{notice || "QCM introuvable."}</p></div>;
  return <main className="page qcm-editor-page"><header className="qcm-editor-head"><div><Link to="/management">← Gestion des QCM</Link><div className="section-label">ÉDITEUR QCM</div><h1>{exam.title}</h1><p>{exam.questions.length} question(s) · {exam.is_published ? "Publié" : "Brouillon"}</p></div><button className="btn btn-secondary" onClick={() => navigate(`/exam/${exam.id}`)}>Prévisualiser comme étudiant</button></header>{notice && <div className="management-notice">{notice}</div>}
    <div className="qcm-editor-layout"><aside className="qcm-question-nav"><button className="btn btn-primary" onClick={newQuestion}>+ Nouvelle question</button><div className="qcm-question-list">{exam.questions.map((q, i) => <button key={q.id} className={selectedId === q.id ? "active" : ""} onClick={() => select(q)}><span>{i + 1}</span><div><strong>Question {i + 1}</strong><small>{q.question_text.replace(/\$.*?\$/g, "math").slice(0, 48)}…</small></div></button>)}{exam.questions.length === 0 && <p>Aucune question.</p>}</div></aside>
      <form className="qcm-question-form" onSubmit={save}><div className="qcm-form-title"><div><span>{selectedId ? "MODIFIER" : "NOUVELLE QUESTION"}</span><h2>{selectedId ? "Question sélectionnée" : "Créer une question"}</h2></div>{selectedId && <button type="button" className="btn btn-secondary btn-sm" onClick={remove}>Supprimer</button>}</div><label>Énoncé de la question<textarea required value={draft.question_text} onChange={(e) => setDraft({ ...draft, question_text: e.target.value })} placeholder={'Texte normal ou LaTeX, par exemple : Soit $S$ dans $\\mathbb{R}$…'}/></label><Preview value={draft.question_text}/><small className="qcm-latex-note">LaTeX est détecté automatiquement entre <code>$...$</code> ou <code>$$...$$</code>.</small><div className="qcm-answers-head"><div><h3>Réponses</h3><p>Choisissez la bonne réponse.</p></div><button type="button" className="btn btn-secondary btn-sm" onClick={() => setDraft({ ...draft, choices: [...draft.choices, { choice_text: "", is_correct: false }] })}>+ Réponse</button></div><div className="qcm-answer-list">{draft.choices.map((choice, i) => <article className={choice.is_correct ? "correct" : ""} key={i}><input type="radio" name="correct" checked={choice.is_correct} onChange={() => setDraft({ ...draft, choices: draft.choices.map((c, index) => ({ ...c, is_correct: index === i })) })}/><b>{String.fromCharCode(65 + i)}</b><div><label>{choice.is_correct ? "Bonne réponse" : `Réponse ${String.fromCharCode(65 + i)}`}<textarea required value={choice.choice_text} onChange={(e) => setChoice(i, { choice_text: e.target.value })} placeholder="Texte ou LaTeX"/></label><Preview value={choice.choice_text}/></div>{draft.choices.length > 2 && <button type="button" onClick={() => { const choices = draft.choices.filter((_, index) => index !== i); if (!choices.some((c) => c.is_correct)) choices[0].is_correct = true; setDraft({ ...draft, choices }); }}>×</button>}</article>)}</div><label>Correction expliquée (visible après la soumission)<textarea value={draft.solution_text} onChange={(e) => setDraft({ ...draft, solution_text: e.target.value })} placeholder="Texte ou LaTeX"/></label><Preview value={draft.solution_text}/><div className="qcm-save-row"><button className="btn btn-primary">{selectedId ? "Enregistrer les modifications" : "Ajouter la question au QCM"}</button></div></form>
    </div></main>;
}
